from typing import Protocol, runtime_checkable


@runtime_checkable
class GarminClient(Protocol):
    def get_sleep_daily(self, start: str, end: str) -> list[dict]: ...
    def get_hrv_data_range(self, start: str, end: str) -> list[dict]: ...
    def get_wellness_daily(self, start: str, end: str) -> list[dict]: ...
    def get_activities_by_date(self, start: str, end: str) -> list[dict]: ...
